### Cars DataFrame Assignment by Atish Landge

In [1]:
from warnings import filterwarnings
filterwarnings ('ignore')

In [2]:
import pandas as pd
path=r"D:\Pandas Assignment\Cars93.csv"
df=pd.read_csv(path,na_values=['','NA'],keep_default_na=False)
A=df
A

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,None,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,None,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

### Q1: Find out car having highest Mileage in city

In [38]:
A.sort_values(by='MPG.city',ascending=False).head(5)

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,None,...,4,151,93,63,34,27.5,10.0,1695,non-USA,Geo Metro
41,42,Honda,Civic,Small,8.4,12.1,15.8,42,46,Driver only,...,4,173,103,67,36,28.0,12.0,2350,non-USA,Honda Civic
82,83,Suzuki,Swift,Small,7.3,8.6,10.0,39,43,None,...,4,161,93,63,34,27.5,10.0,1965,non-USA,Suzuki Swift
79,80,Subaru,Justy,Small,7.3,8.4,9.5,33,37,None,...,4,146,90,60,32,23.5,10.0,2045,non-USA,Subaru Justy
83,84,Toyota,Tercel,Small,7.8,9.8,11.8,32,37,Driver only,...,5,162,94,65,36,24.0,11.0,2055,non-USA,Toyota Tercel

### Q2:Find out Models of cars which are having Price between 17 and 25

In [18]:
fil1 =A['Price']>=17
fil2 =A['Price']<=25
fil=fil1 & fil2
A[fil]

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
6,7,Buick,LeSabre,Large,19.9,20.8,21.7,19,28,Driver only,...,6,200,111,74,42,30.5,17.0,3470,USA,Buick LeSabre
7,8,Buick,Roadmaster,Large,22.6,23.7,24.9,16,25,Driver only,...,6,216,116,78,45,30.5,21.0,4105,USA,Buick Roadmaster
17,18,Chevrolet,Caprice,Large,18.0,18.8,19.6,17,26,Driver only,...,6,214,116,77,42,29.5,20.0,3910,USA,Chevrolet Caprice
19,20,Chrylser,Concorde,Large,18.4,18.4,18.4,20,28,Driver & Passenger,...,6,203,113,74,40,31.0,15.0,3515,USA,Chrylser Concorde
25,26,Dodge,Caravan,Van,13.6,19.0,24.4,17,21,Driver only,...,7,175,112,72,42,26.5,NaN,3705,USA,Dodge Caravan
29,30,Eagle,Vision,Large,17.5,19.3,21.2,20,28,Driver & Passenger,...,6,202,113,74,40,30.0,15.0,3490,USA,Eagle Vision
35,36,Ford,Aerostar,Van,14.5,19.9,25.3,15,20,Driver only,...,7,176,119,72,45,30.0,NaN,3735,USA,Ford Aerostar
36,37,Ford,Taurus,Midsize,15.6,20.2,24.8,21,30,Driver only,...,5,192,106,71,40,27.5,18.0,3325,USA,Ford Taurus
37,38,Ford,Crown_Victoria,Large,20.1,20.9,21.7,18,26,Driver only,...,6,212,114,78,43,30.0,21.0,3950,USA,Ford Crown_Victoria
40,41,Honda,Prelude,Sporty,17.0,19.8,22.7,24,31,Driver & Passenger,...,4,175,100,70,39,23.5,8.0,2865,non-USA,Honda Prelude
42,43,Honda,Accord,Compact,13.8,17.5,21.2,24,31,Driver & Passenger,...,4,185,107,67,41,28.0,14.0,3040,non-USA,Honda Accord
55,56,Mazda,MPV,Van,16.6,19.1,21.7,18,24,None,...,7,190,110,72,39,27.5,NaN,3735,non-USA,Mazda MPV
65,66,Nissan,Quest,Van,16.7,19.1,21.5,17,23,None,...,7,190,112,74,41,27.0,NaN,4100,non-USA,Nissan Quest
66,67,Nissan,Maxima,Midsize,21.0,21.5,22.0,21,26,Driver only,...,5,188,104,69,41,28.5,14.0,3200,non-USA,Nissan Maxima
69,70,Oldsmobile,Silhouette,Van,19.5,19.5,19.5,18,23,None,...,7,194,110,74,44,30.5,NaN,3715,USA,Oldsmobile Silhouette
70,71,Oldsmobile,Eighty-Eight,Large,19.5,20.7,21.9,19,28,Driver only,...,6,201,111,74,42,31.5,17.0,3470,USA,Oldsmobile Eighty-Eight
74,75,Pontiac,Firebird,Sporty,14.0,17.7,21.4,19,28,Driver & Passenger,...,4,196,101,75,43,25.0,13.0,3240,USA,Pontiac Firebird
75,76,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,19,27,None,...,5,195,108,72,41,28.5,16.0,3450,USA,Pontiac Grand_Prix
76,77,Pontiac,Bonneville,Large,19.4,24.4,29.4,19,28,Driver & Passenger,...,6,177,111,74,43,30.5,18.0,3495,USA,Pontiac Bonneville
81,82,Subaru,Legacy,Compact,16.3,19.5,22.7,23,30,Driver only,...,5,179,102,67,37,27.0,14.0,3085,non-USA,Subaru Legacy
84,85,Toyota,Celica,Sporty,14.2,18.4,22.6,25,32,Driver only,...,4,174,99,69,39,23.0,13.0,2950,non-USA,Toyota Celica
85,86,Toyota,Camry,Midsize,15.2,18.2,21.2,22,29,Driver only,...,5,188,103,70,38,28.5,15.0,3030,non-USA,Toyota Camry
86,87,Toyota,Previa,Van,18.9,22.7,26.6,18,22,Driver only,...,7,187,113,71,41,35.0,NaN,3785,non-USA,Toyota Previa
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,None,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,None,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240

In [20]:
A.query("Price>=17 and Price<=25")

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
6,7,Buick,LeSabre,Large,19.9,20.8,21.7,19,28,Driver only,...,6,200,111,74,42,30.5,17.0,3470,USA,Buick LeSabre
7,8,Buick,Roadmaster,Large,22.6,23.7,24.9,16,25,Driver only,...,6,216,116,78,45,30.5,21.0,4105,USA,Buick Roadmaster
17,18,Chevrolet,Caprice,Large,18.0,18.8,19.6,17,26,Driver only,...,6,214,116,77,42,29.5,20.0,3910,USA,Chevrolet Caprice
19,20,Chrylser,Concorde,Large,18.4,18.4,18.4,20,28,Driver & Passenger,...,6,203,113,74,40,31.0,15.0,3515,USA,Chrylser Concorde
25,26,Dodge,Caravan,Van,13.6,19.0,24.4,17,21,Driver only,...,7,175,112,72,42,26.5,NaN,3705,USA,Dodge Caravan
29,30,Eagle,Vision,Large,17.5,19.3,21.2,20,28,Driver & Passenger,...,6,202,113,74,40,30.0,15.0,3490,USA,Eagle Vision
35,36,Ford,Aerostar,Van,14.5,19.9,25.3,15,20,Driver only,...,7,176,119,72,45,30.0,NaN,3735,USA,Ford Aerostar
36,37,Ford,Taurus,Midsize,15.6,20.2,24.8,21,30,Driver only,...,5,192,106,71,40,27.5,18.0,3325,USA,Ford Taurus
37,38,Ford,Crown_Victoria,Large,20.1,20.9,21.7,18,26,Driver only,...,6,212,114,78,43,30.0,21.0,3950,USA,Ford Crown_Victoria
40,41,Honda,Prelude,Sporty,17.0,19.8,22.7,24,31,Driver & Passenger,...,4,175,100,70,39,23.5,8.0,2865,non-USA,Honda Prelude
42,43,Honda,Accord,Compact,13.8,17.5,21.2,24,31,Driver & Passenger,...,4,185,107,67,41,28.0,14.0,3040,non-USA,Honda Accord
55,56,Mazda,MPV,Van,16.6,19.1,21.7,18,24,None,...,7,190,110,72,39,27.5,NaN,3735,non-USA,Mazda MPV
65,66,Nissan,Quest,Van,16.7,19.1,21.5,17,23,None,...,7,190,112,74,41,27.0,NaN,4100,non-USA,Nissan Quest
66,67,Nissan,Maxima,Midsize,21.0,21.5,22.0,21,26,Driver only,...,5,188,104,69,41,28.5,14.0,3200,non-USA,Nissan Maxima
69,70,Oldsmobile,Silhouette,Van,19.5,19.5,19.5,18,23,None,...,7,194,110,74,44,30.5,NaN,3715,USA,Oldsmobile Silhouette
70,71,Oldsmobile,Eighty-Eight,Large,19.5,20.7,21.9,19,28,Driver only,...,6,201,111,74,42,31.5,17.0,3470,USA,Oldsmobile Eighty-Eight
74,75,Pontiac,Firebird,Sporty,14.0,17.7,21.4,19,28,Driver & Passenger,...,4,196,101,75,43,25.0,13.0,3240,USA,Pontiac Firebird
75,76,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,19,27,None,...,5,195,108,72,41,28.5,16.0,3450,USA,Pontiac Grand_Prix
76,77,Pontiac,Bonneville,Large,19.4,24.4,29.4,19,28,Driver & Passenger,...,6,177,111,74,43,30.5,18.0,3495,USA,Pontiac Bonneville
81,82,Subaru,Legacy,Compact,16.3,19.5,22.7,23,30,Driver only,...,5,179,102,67,37,27.0,14.0,3085,non-USA,Subaru Legacy
84,85,Toyota,Celica,Sporty,14.2,18.4,22.6,25,32,Driver only,...,4,174,99,69,39,23.0,13.0,2950,non-USA,Toyota Celica
85,86,Toyota,Camry,Midsize,15.2,18.2,21.2,22,29,Driver only,...,5,188,103,70,38,28.5,15.0,3030,non-USA,Toyota Camry
86,87,Toyota,Previa,Van,18.9,22.7,26.6,18,22,Driver only,...,7,187,113,71,41,35.0,NaN,3785,non-USA,Toyota Previa
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,None,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,None,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240

### Q3: Find out top 7 most fuel economic cars for highway

In [37]:
A.sort_values(by='MPG.highway',ascending=False).head(7)[['Manufacturer','Model','MPG.highway']]

   Manufacturer   Model  MPG.highway
38          Geo   Metro           50
41        Honda   Civic           46
82       Suzuki   Swift           43
72      Pontiac  LeMans           41
78       Saturn      SL           38
83       Toyota  Tercel           37
79       Subaru   Justy           37

### Q4:Find out Models of cars having no AirBags and which are of compact type whose price is below 20.

In [62]:
fil1=A['AirBags']=='None'
fil2=A['Type']=='Compact'
fil3=A['Price']<=20
fil=(fil1 & fil2 & fil3)
A[fil]

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
11,12,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25,36,None,...,5,182,101,66,38,25.0,13.0,2490,USA,Chevrolet Cavalier
32,33,Ford,Tempo,Compact,10.4,11.3,12.2,22,27,None,...,5,177,100,68,39,27.5,13.0,2690,USA,Ford Tempo
67,68,Oldsmobile,Achieva,Compact,13.0,13.5,14.0,24,31,None,...,5,188,103,67,39,28.0,14.0,2910,USA,Oldsmobile Achieva
73,74,Pontiac,Sunbird,Compact,9.4,11.1,12.8,23,31,None,...,5,181,101,66,39,25.0,13.0,2575,USA,Pontiac Sunbird
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat

In [60]:
A.query("(AirBags=='None' and Type=='Compact' and Price<=20)")

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
11,12,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25,36,None,...,5,182,101,66,38,25.0,13.0,2490,USA,Chevrolet Cavalier
32,33,Ford,Tempo,Compact,10.4,11.3,12.2,22,27,None,...,5,177,100,68,39,27.5,13.0,2690,USA,Ford Tempo
67,68,Oldsmobile,Achieva,Compact,13.0,13.5,14.0,24,31,None,...,5,188,103,67,39,28.0,14.0,2910,USA,Oldsmobile Achieva
73,74,Pontiac,Sunbird,Compact,9.4,11.1,12.8,23,31,None,...,5,181,101,66,39,25.0,13.0,2575,USA,Pontiac Sunbird
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat

### Q5:Find out top 7 most fuel economic cars for city, show results in sorted manner based on Horsepower.

In [15]:
A.nlargest(7,'MPG.city')[['Model','MPG.city','Horsepower']]

      Model  MPG.city  Horsepower
38    Metro        46          55
41    Civic        42         102
82    Swift        39          70
79    Justy        33          73
83   Tercel        32          82
30  Festiva        31          63
72   LeMans        31          74

### Step 2

In [35]:
B=A.sort_values(by='MPG.city' ,ascending=False).head(7)[["Manufacturer",
                                                           "Model",
                                                           "MPG.city",
    
                                                         "Horsepower"]]
B

   Manufacturer    Model  MPG.city  Horsepower
38          Geo    Metro        46          55
41        Honda    Civic        42         102
82       Suzuki    Swift        39          70
79       Subaru    Justy        33          73
83       Toyota   Tercel        32          82
72      Pontiac   LeMans        31          74
30         Ford  Festiva        31          63

In [36]:
B.sort_values(by='Horsepower',ascending=False)

   Manufacturer    Model  MPG.city  Horsepower
41        Honda    Civic        42         102
83       Toyota   Tercel        32          82
72      Pontiac   LeMans        31          74
79       Subaru    Justy        33          73
82       Suzuki    Swift        39          70
30         Ford  Festiva        31          63
38          Geo    Metro        46          55

###### Q6:Find out Cars having mileage of more than 15 miles in city

In [55]:
fil3=A[A['MPG.city']>15]
fil3

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,None,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,None,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

### Step 2

In [32]:
A.query("`MPG.city`>15")

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,None,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,None,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

### Q7:Find out Cars with US based origin¶

In [30]:
A.query("Origin=='USA'")[['Model','Manufacturer','Origin']]

             Model Manufacturer Origin
5          Century        Buick    USA
6          LeSabre        Buick    USA
7       Roadmaster        Buick    USA
8          Riviera        Buick    USA
9          DeVille     Cadillac    USA
10         Seville     Cadillac    USA
11        Cavalier    Chevrolet    USA
12         Corsica    Chevrolet    USA
13          Camaro    Chevrolet    USA
14          Lumina    Chevrolet    USA
15      Lumina_APV    Chevrolet    USA
16           Astro    Chevrolet    USA
17         Caprice    Chevrolet    USA
18        Corvette    Chevrolet    USA
19        Concorde     Chrylser    USA
20         LeBaron     Chrysler    USA
21        Imperial     Chrysler    USA
22            Colt        Dodge    USA
23          Shadow        Dodge    USA
24          Spirit        Dodge    USA
25         Caravan        Dodge    USA
26         Dynasty        Dodge    USA
27         Stealth        Dodge    USA
28          Summit        Eagle    USA
29          Vision        Eagle    USA
30         Festiva         Ford    USA
31          Escort         Ford    USA
32           Tempo         Ford    USA
33         Mustang         Ford    USA
34           Probe         Ford    USA
35        Aerostar         Ford    USA
36          Taurus         Ford    USA
37  Crown_Victoria         Ford    USA
50     Continental      Lincoln    USA
51        Town_Car      Lincoln    USA
59           Capri      Mercury    USA
60          Cougar      Mercury    USA
67         Achieva   Oldsmobile    USA
68   Cutlass_Ciera   Oldsmobile    USA
69      Silhouette   Oldsmobile    USA
70    Eighty-Eight   Oldsmobile    USA
71           Laser     Plymouth    USA
72          LeMans      Pontiac    USA
73         Sunbird      Pontiac    USA
74        Firebird      Pontiac    USA
75      Grand_Prix      Pontiac    USA
76      Bonneville      Pontiac    USA
78              SL       Saturn    USA

### Q8:Find out Cars with no airbags and which are compact in type, from the output retrieve only Model, Mileage in city, Type, Airbags

In [24]:
A.query("AirBags=='None'and Type=='Compact'")[['Model',
                                            'MPG.city',
                                        'Type','AirBags']]

       Model  MPG.city     Type AirBags
11  Cavalier        25  Compact    None
32     Tempo        22  Compact    None
67   Achieva        24  Compact    None
73   Sunbird        23  Compact    None
89    Passat        21  Compact    None

### Q9: Find out cars with Mileage in city more than 15 which are compact in type.

In [29]:
A.query("`MPG.city`>=15 and Type=='Compact'")[['Model','MPG.city']]

       Model  MPG.city
2         90        20
11  Cavalier        25
12   Corsica        25
20   LeBaron        23
24    Spirit        22
32     Tempo        22
42    Accord        24
54       626        26
57      190E        20
64    Altima        24
67   Achieva        24
73   Sunbird        23
77       900        20
81    Legacy        23
89    Passat        21
91       240        21